In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')
body = pd.read_csv(r'C:\Users\suhye\.vscode\Adp실기\데이터분석전문가_파이썬\6.머신러닝_지도학습\bodyPerformance.csv')

In [3]:
body['gender'] = np.where(body['gender'] == 'M',0,1)
mapping = {'A':0,'B':1,'C':2,'D':4}
body['class_2'] = body['class'].map(mapping)

body

age  gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0      27.0       1      172.3      75.24        21.3       80.0     130.0   
1      25.0       1      165.0      55.80        15.7       77.0     126.0   
2      31.0       1      179.6      78.00        20.1       92.0     152.0   
3      32.0       1      174.5      71.10        18.4       76.0     147.0   
4      28.0       1      173.8      67.70        17.1       70.0     127.0   
...     ...     ...        ...        ...         ...        ...       ...   
13388  25.0       1      172.1      71.80        16.2       74.0     141.0   
13389  21.0       1      179.7      63.90        12.1       74.0     128.0   
13390  39.0       1      177.2      80.50        20.1       78.0     132.0   
13391  64.0       1      146.1      57.70        40.4       68.0     121.0   
13392  34.0       1      164.0      66.10        19.5       82.0     150.0   

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm  \
0           54.9                     18.4            60.0          217.0   
1           36.4                     16.3            53.0          229.0   
2           44.8                     12.0            49.0          181.0   
3           41.4                     15.2            53.0          219.0   
4           43.5                     27.1            45.0          217.0   
...          ...                      ...             ...            ...   
13388       35.8                     17.4            47.0          198.0   
13389       33.0                      1.1            48.0          167.0   
13390       63.5                     16.4            45.0          229.0   
13391       19.3                      9.2             0.0           75.0   
13392       35.9                      7.1            51.0          180.0   

      class  class_2  
0         C        2  
1         A        0  
2         C        2  
3         B        1  
4         B        1  
...     ...      ...  
13388     C        2  
13389     D        4  
13390     A        0  
13391     D        4  
13392     C        2  

[13393 rows x 13 columns]

In [4]:
from sklearn.model_selection import train_test_split

feature_columns = list(body.columns.difference(['class','class_2']))

x = body[feature_columns]
y = body['class_2']

x_train, x_test, y_train, y_test = train_test_split(x,y,stratify=y,train_size=0.7,random_state=1)

print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(9375, 11) (4018, 11) (9375,) (4018,)


In [5]:
from sklearn.linear_model import LogisticRegression

softm = LogisticRegression(multi_class = 'multinomial',solver='lbfgs',C=10)
softm.fit(x_train,y_train)

LogisticRegression(C=10, multi_class='multinomial')

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score

pred = softm.predict(x_test)

test_cm = confusion_matrix(y_test,pred)
test_acc = accuracy_score(y_test,pred)

print(test_cm)
print('정확도\t{}'.format(round(test_acc*100,2)))

[[713 254  37   0]
 [274 397 301  32]
 [ 97 203 524 181]
 [ 13  64 158 770]]
정확도	59.83


In [8]:
softm.predict([x_test.iloc[-1,:]])

array([0], dtype=int64)

In [9]:
softm.predict_proba([x_test.iloc[-1,:]])

array([[0.63470255, 0.30342206, 0.06028514, 0.00159025]])